openapi: 3.0.0
info:
  version: 1.0.0
  title: Nabaaang API
  description: Nabaaang API 문서입니다
servers:
  - url: "http://localhost:4000"
components:
  schemas: 
    Channel:
      $ref: ../channel/components.yaml#/Channel
    Message:
      $ref: ../message/components.yaml#/Message

paths:
  $ref: ../channel/paths.yaml

