const GOOGLE_CLIENT_ID =
    process.env.REACT_APP_GOOGLE_CLIENT_ID ||
    process.env.STORYBOOK_REACT_APP_GOOGLE_CLIENT_ID;

const GOOGLE_REDIRECT_URI =
    process.env.REACT_APP_GOOGLE_REDIRECT_URI ||
    process.env.STORYBOOK_REACT_APP_GOOGLE_REDIRECT_URI;

export { GOOGLE_CLIENT_ID, GOOGLE_REDIRECT_URI };
